@luogu=https://www.luogu.com.cn
###
GET https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY

###
GET {{luogu}}/problem/list
?_contentOnly
###
GET {{luogu}}/ranking
?_contentOnly
###
GET {{luogu}}/contest/list
?_contentOnly
&page=1